### PR TITLE
refactor(Nav): remove ReactTransitionGroup; adjust styles to accommodate

### LINKED ISSUE #42: Find a way to remove `react-transition-group`
We are shipping a big chunk of JS by using that dependency and that's only used on the nav.
@andrewrubin [suggested](https://github.com/wethegit/corgi/pull/38#discussion_r1230251159) a solution that I think we should make it our default.

### LINKED ISSUE #59: Nav: clean up HTML elements and ARIA attributes
- We should be using `<ul>` instead of `<menu>`
- The `aria-expanded` attribute should be on the toggle button, not the nav list
  - Let's add `aria-controls` to the main `<nav>` itself

### PR DESCRIPTION
**Pull request by andrewrubin**
Closes #42 
Closes #59 

# What this does
- removes `react-transition-group` dependency
- removes `PageTransition` component
- refactors the `<Nav />` component to **not** use `CSSTransition`
- adjusts `<Nav />` CSS to hide using CSS transform and opacity properties, rather than mounting + unmounting
- adds quality-of-life updates for animating the nav in/out, see below, hopefully not too opinionated:

nav-animation-controls

## To test locally
- go to your corgi repo and run `node cli/bin/index.js project nav-test`
- cd into the new `nav-test` directory, install deps, and open the local server.

### CODE REVIEW

**Comment by NicholasLancey** [comment]
@andrewrubin I'm getting an error when running this. It looks like `react-transition-group` is still being used in `page-transition` - or have I just set up my build incorrectly?

**Comment by andrewrubin** [comment]
Thanks for the heads up @NicholasLancey. I wonder why I was not getting errors yesterday when testing this. Converting this to a draft PR while I sort that out.

**Comment by andrewrubin** [comment]
@wethegit/reviewers Going to keep this open as a draft for the time being — 

The gameplan is as follows:
- Remove ReactTransitionGroup
- Refactor corgi CLI's project template to remove PageTransition and all associated contexts
- Keep the navigation refactor as it exists in this PR

This will give us a clean slate to pursue page transitions in the future if we so choose.

**Comment by andrewrubin** [comment]
Have not forgotten about this. Will try to tackle it in the next week or so.

**Comment by andrewrubin** [comment]
Hey @wethegit/reviewers , this one is ready to go.

**Review by marlonmarcello — APPROVED** [review]
Feels good to get rid of this.

**Pull request merged**
