### PR TITLE
Add support for deep-merge of YAML data

### LINKED ISSUE #104: Allow for deep merge on index YAML files
Currently if you have the following in your `index.yml` file…
```yaml
footer:
  logo: "my-logo.png"
  alt: "Company Name logo"
```

You cannot inherit those nested properties in a locale YAML file like so:
```yaml
# en-us.yml

footer:
  legal: © 2024 Some Company. All rights reserved.
  # logo not inherited
  # alt not inherited 
```

### PR DESCRIPTION
**Pull request by andrewrubin**
## Overview
This adds support for **nested** locale-specific overrides of YAML data. 
Closes #104 

Also included:
- minor dependabot fixes which are already in `main`
- minor changes to variable naming in `page-setup.js`
- minor updates to documentation 

## What problem does this solve?
Currently, overriding YAML data from the `index.yml` file simply overwrites the first identical key. For example, if you had:
```yml
# index.yml
section:
  title: Our clients love us
  body: Lorem ipsum dolor…
  clientList: ['amazon', 'canadian tire', 'best buy']
```
and you wanted to alter the client list for the UK version of the section:
```yml
# en-gb.yml
section:
  clientList: ['smyths', 'game']
```
You would lose the `title` and `body` properties entirely. The `section` key would only contain your new `clientList`.

## Solution
Continuing with the example above, this update will *preserve* those `title` and `body` key/value pairs. This works with deeply-nested objects as well.

This has many implications for speeding up workflow around localization. Exciting stuff.

## Example
The video below shows an example of this in action on a fresh corgi project. I'm defining all the "global" navigation items for an example app, and then only overwriting the `label` property of each, for the locale-specific page render. The idea here is that the URL enpoints are always the same, so there's no need to re-declare them on every locale file.

https://github.com/wethegit/corgi/assets/30575213/eda04117-428f-4aeb-acba-13b78d1b2273

(shout out to @liamegan for tag-teaming this deepMerge function with me!)

## Testing this
The easiest way to test this update is to reference the package binary directly, and bootstrap a sample project:
1. Check out this branch by running `git checkout feature/template/yaml-deep-merge`
2. `cd` into the project's root directory if you're not already there, and run `node ./cli/bin/index.js project test-corgi-build`
3. Run the following commands to start the project: 
```shell
cd test-corgi-build
nvm use # or n auto
npm install
npm start
```

### CODE REVIEW

**Comment by rvno** [comment]
@andrewrubin can you share a screenshot of what you have within `home-body.jsx` please?

For my current test I'm simply rendering the key value pairs for each `item` object, but when omitting the keys that I want to "inherit", they end up being undefined.


image
image
image

**Comment by rvno** [comment]
Ah nevermind, my setup was flawed in that I had the "globals" setup in `en-us` rather than `index.yml`, ignore!

**Comment by rvno** [comment]
@andrewrubin the deepMerge works for me granted the number of items within a `locale` match the number of items in `index.yml` but had some thoughts - also, happy to discuss over a huddle if it's easier.

Similar to the TCG conversation we had re: omitting/overriding, would it be useful in this PR to allow users an option to flag objects that should/should not be deepMerged or is it more appropriate to have the user figure out what is the ideal "base case" object for given scenario?
 
 
If for example, in `fr-ca.yaml`, we omit an item, the result of the deepMerge still gives us 3 items, which could be seen as a bit confusing if we wanted to omit the 3rd items in a scenario where a specific locale(s) doesn't have said 3rd item. Although this could be solved by having the user update the "base case" and overriding/adding values as needed for whatever locale, I wonder what seems more effective - updating the base case versus adding a whitelist/blacklist/flag option within locale overrides - especially considering how content matrices are subject to change.

This may not apply but I'm also imagining In the case of say a button (recalling TCG's Shop/Events/Retailer) [https://gitlab.com/thepokemoncompanyinternational/podx/ms/tcg-pokemon/-/merge_requests/63](pr for ref) - there could be excess properties inherited when they may not be appropriate for a given instance.

**Comment by andrewrubin** [comment]
@rvno great points, all around.

I went through a similar back-and-forth in my mind when deciding how this should behave. Since it's a _deep_ merge, it—necessarily—means that objects down the tree are merged rather than replaced or omitted. This is partly why I wrote that warning ⚠️ in the `mergeArray` source docs.

Let me know if you don't agree at all, but in my mind, the less options and features here, the better. Adding flags to around whether to deep merge or not might lead to overwhelming complexity. I think the solution there is better data design on the part of the developer themselves; i.e. don't add things to the index file if they're not legitimately shared across all locales.

What do you think?

**Comment by rvno** [comment]
> @rvno great points, all around.
> 
> I went through a similar back-and-forth in my mind when deciding how this should behave. Since it's a _deep_ merge, it—necessarily—means that objects down the tree are merged rather than replaced or omitted. This is partly why I wrote that warning ⚠️ in the `mergeArray` source docs.
> 
> Let me know if you don't agree at all, but in my mind, the less options and features here, the better. Adding flags around whether to deep merge or not might lead to overwhelming complexity. I think the solution there is better data design on the part of the developer themselves; i.e. don't add things to the index file if they're not legitimately shared across all locales.
> 
> What do you think?

That's cool with me. I think I mentally extended the potential usage of the merge capability to the point of trying to have as much yaml as possible in the index, but in the end came back to asking what will the data look like and what the use cases would be.

**Review by rvno — APPROVED** [review]

**Comment by andrewrubin** [comment]
@rvno here's (maybe) a more practical example of this thing's usage. 

Simply overriding a value nested in a `footer` object. With the current behavior, we'd have to re-declare _every_ other key+value inside the footer in order for a small override like this logo to be possible

Screen Shot 2024-06-26 at 10 57 25 AM

**Pull request merged**
