### PR TITLE
fix: ensures locale config is source of truth

### PR DESCRIPTION
**Pull request by marlonmarcello**
This small fix to page setup ensures that we are configuring our locales instead of basing ourselves on the files inside the locales directory.  

The main reason being that it removes ambiguity.  
The app is split between two sources of truth when it comes to locales at the moment.
`config-locales.js` is used to generate `alternate` lang metas and also provide data to other areas of the app like in the `_document` and `link` components.
But when it comes to generating the pages we use the `locales` directory as our source of truth instead. 

Also this change:
1. Ensures that locale paths are set so we don't get `undefined`s in the source code
2. Only builds locales that are configured, creating an extra layer in avoiding leaking any unfinished `yaml`s
3. Ensures that `config-locales` is the ONLY place to determine the app's locale tree

I am happy to go the other way around and favour convention over configuration, but I think we should pick one.

### CODE REVIEW

**Review by andrewrubin — COMMENTED** [review]
Love this @marlonmarcello, thank you for the update. This also fixes #56, so, yay.

I was looking through the config file though, and I noticed we have to enter the locales we want twice — once in the `locales` variable, and once in the `localeMap`. Just as a small improvement, I suggest we derive the `locales` variable from the `localesMap`, instead of hard coding it. That way there's literally only ever _one_ source of truth. Thoughts? I can make this update if ya like.

Thanks!

**Comment by marlonmarcello** [comment]
> Love this @marlonmarcello, thank you for the update. This also fixes #56, so, yay.
> 
> I was looking through the config file though, and I noticed we have to enter the locales we want twice — once in the `locales` variable, and once in the `localeMap`. Just as a small improvement, I suggest we derive the `locales` variable from the `localesMap`, instead of hard coding it. That way there's literally only ever _one_ source of truth. Thoughts? I can make this update if ya like.
> 
> Thanks!

That's a great idea @andrewrubin ! Feel free to tackle that. I won't be able to today

**Comment by andrewrubin** [comment]
That's done @marlonmarcello . I tested it and all works just fine. Have a look and then feel free to merge to `dev` if you like what you see.

**Review by andrewrubin — APPROVED** [review]

**Comment by marlonmarcello** [comment]
Thanks @andrewrubin 🍰 
This doesn't break anything, do we wanna ship it now wit a minor version?

**Comment by andrewrubin** [comment]
Yeah sounds good @marlonmarcello. I'll merge and then make a release PR for everyone to have eyes on

**Pull request merged**
